# Generated by Django 2.2.6 on 2019-11-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('LG', 'Large'), ('SM', 'Small')], default='SM', max_length=2)),
            ],
        ),
    ]
