# Generated by Django 2.2.6 on 2019-11-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platter',
        ),
    ]
