# Generated by Django 2.2.6 on 2019-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_category_dish_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='category',
            field=models.ForeignKey(blank=True, on_delete='cascade', related_name='toppings', to='orders.Category'),
        ),
    ]
