# Generated by Django 2.2.6 on 2019-11-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191114_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='is_steak_and_cheese',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='topping',
            name='category',
        ),
        migrations.AddField(
            model_name='topping',
            name='category',
            field=models.ManyToManyField(related_name='toppings', to='orders.Category'),
        ),
    ]
