# Generated by Django 2.2.6 on 2019-11-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191114_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='price',
            new_name='large_price',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='size',
        ),
        migrations.AddField(
            model_name='dish',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
    ]
