# Generated by Django 2.2.6 on 2019-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191114_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
