# Generated by Django 2.2.6 on 2019-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_orderitem_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='num_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
