# Generated by Django 2.2.6 on 2019-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191118_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='items', to='orders.Topping'),
        ),
    ]
