# Generated by Django 2.2.6 on 2019-11-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191118_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('LG', 'Large'), ('SM', 'Small')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
