# Generated by Django 2.2.6 on 2019-11-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20191119_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
