# Generated by Django 2.2.6 on 2019-11-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191119_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='0000000000', editable=False, max_length=10, null=True),
        ),
    ]
