# Generated by Django 2.2.6 on 2019-11-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191120_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(blank=True, default=-1, editable=False, null=True),
        ),
    ]
